export const ERROR_CODES = {
  // Auth
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_TOKEN_INVALID: 'AUTH_TOKEN_INVALID',
  AUTH_TOKEN_REVOKED: 'AUTH_TOKEN_REVOKED',
  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  USER_ALREADY_EXISTS: 'USER_ALREADY_EXISTS',
  // Validation
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  // Generic
  NOT_FOUND: 'NOT_FOUND',
  FORBIDDEN: 'FORBIDDEN',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
} as const;

/**
 * Canonical error-code namespace used by server responses.
 * Matches `server/src/lib/errors.ts`.
 */
export const CANONICAL_ERROR_CODES = {
  // Auth (1xxx)
  UNAUTHORIZED: 'AUTH_001',
  FORBIDDEN: 'AUTH_002',
  TOKEN_EXPIRED: 'AUTH_003',
  TOKEN_INVALID: 'AUTH_004',
  TOKEN_REVOKED: 'AUTH_005',
  ACCOUNT_LOCKED: 'AUTH_006',
  ACCOUNT_NOT_VERIFIED: 'AUTH_007',
  INVALID_CREDENTIALS: 'AUTH_008',
  EMAIL_ALREADY_EXISTS: 'AUTH_009',
  PASSWORD_TOO_WEAK: 'AUTH_010',
  REFRESH_TOKEN_MISSING: 'AUTH_011',
  SESSION_EXPIRED: 'AUTH_012',

  // Validation (2xxx)
  VALIDATION_FAILED: 'VAL_001',
  INVALID_INPUT: 'VAL_002',
  MISSING_REQUIRED_FIELD: 'VAL_003',
  INVALID_FORMAT: 'VAL_004',
  PAYLOAD_TOO_LARGE: 'VAL_005',

  // Resource (3xxx)
  NOT_FOUND: 'RES_001',
  ALREADY_EXISTS: 'RES_002',
  CONFLICT: 'RES_003',
  GONE: 'RES_004',

  // Business (4xxx)
  SLOT_UNAVAILABLE: 'BIZ_001',
  SESSION_NOT_CANCELLABLE: 'BIZ_002',
  PAYMENT_FAILED: 'BIZ_003',
  PAYMENT_DUPLICATE: 'BIZ_004',
  INSUFFICIENT_BALANCE: 'BIZ_005',
  BOOKING_TOO_SOON: 'BIZ_006',
  ONBOARDING_INCOMPLETE: 'BIZ_007',
  DAILY_LIMIT_REACHED: 'BIZ_008',
  THERAPIST_UNAVAILABLE: 'BIZ_009',

  // Rate limit (5xxx)
  RATE_LIMITED: 'RATE_001',
  TOO_MANY_REQUESTS: 'RATE_002',

  // Server (9xxx)
  INTERNAL: 'SRV_001',
  SERVICE_UNAVAILABLE: 'SRV_002',
  DATABASE_ERROR: 'SRV_003',
  EXTERNAL_SERVICE_ERROR: 'SRV_004',
  NOT_IMPLEMENTED: 'SRV_005',
} as const;

export type CanonicalErrorCode = (typeof CANONICAL_ERROR_CODES)[keyof typeof CANONICAL_ERROR_CODES];

/**
 * Backward-compatibility aliases:
 * old/legacy error strings -> canonical error code.
 */
export const ERROR_CODE_ALIASES_TO_CANONICAL: Record<string, CanonicalErrorCode> = {
  // Legacy shared constants
  [ERROR_CODES.AUTH_INVALID_CREDENTIALS]: CANONICAL_ERROR_CODES.INVALID_CREDENTIALS,
  [ERROR_CODES.AUTH_ACCOUNT_LOCKED]: CANONICAL_ERROR_CODES.ACCOUNT_LOCKED,
  [ERROR_CODES.AUTH_EMAIL_EXISTS]: CANONICAL_ERROR_CODES.EMAIL_ALREADY_EXISTS,
  [ERROR_CODES.AUTH_TOKEN_EXPIRED]: CANONICAL_ERROR_CODES.TOKEN_EXPIRED,
  [ERROR_CODES.AUTH_TOKEN_INVALID]: CANONICAL_ERROR_CODES.TOKEN_INVALID,
  [ERROR_CODES.AUTH_TOKEN_REVOKED]: CANONICAL_ERROR_CODES.TOKEN_REVOKED,
  [ERROR_CODES.USER_NOT_FOUND]: CANONICAL_ERROR_CODES.NOT_FOUND,
  [ERROR_CODES.USER_ALREADY_EXISTS]: CANONICAL_ERROR_CODES.ALREADY_EXISTS,
  [ERROR_CODES.VALIDATION_FAILED]: CANONICAL_ERROR_CODES.VALIDATION_FAILED,
  [ERROR_CODES.NOT_FOUND]: CANONICAL_ERROR_CODES.NOT_FOUND,
  [ERROR_CODES.FORBIDDEN]: CANONICAL_ERROR_CODES.FORBIDDEN,
  [ERROR_CODES.INTERNAL_ERROR]: CANONICAL_ERROR_CODES.INTERNAL,
  [ERROR_CODES.RATE_LIMIT_EXCEEDED]: CANONICAL_ERROR_CODES.RATE_LIMITED,

  // Historical literals still seen in middleware/controllers/clients
  UNAUTHORIZED: CANONICAL_ERROR_CODES.UNAUTHORIZED,
  AUTHENTICATION_ERROR: CANONICAL_ERROR_CODES.UNAUTHORIZED,
  AUTHORIZATION_ERROR: CANONICAL_ERROR_CODES.FORBIDDEN,
  TOKEN_EXPIRED: CANONICAL_ERROR_CODES.TOKEN_EXPIRED,
  TOKEN_INVALID: CANONICAL_ERROR_CODES.TOKEN_INVALID,
  TOKEN_REVOKED: CANONICAL_ERROR_CODES.TOKEN_REVOKED,
  INVALID_CREDENTIALS: CANONICAL_ERROR_CODES.INVALID_CREDENTIALS,
  REFRESH_TOKEN_MISSING: CANONICAL_ERROR_CODES.REFRESH_TOKEN_MISSING,
  SESSION_EXPIRED: CANONICAL_ERROR_CODES.SESSION_EXPIRED,
  VALIDATION_ERROR: CANONICAL_ERROR_CODES.VALIDATION_FAILED,
  MISSING_FIELD: CANONICAL_ERROR_CODES.MISSING_REQUIRED_FIELD,
  INVALID_FORMAT: CANONICAL_ERROR_CODES.INVALID_FORMAT,
  CONFLICT: CANONICAL_ERROR_CODES.CONFLICT,
  ALREADY_EXISTS: CANONICAL_ERROR_CODES.ALREADY_EXISTS,
  INTERNAL_SERVER_ERROR: CANONICAL_ERROR_CODES.INTERNAL,
  RATE_LIMITED: CANONICAL_ERROR_CODES.RATE_LIMITED,
  TOO_MANY_REQUESTS: CANONICAL_ERROR_CODES.TOO_MANY_REQUESTS,
  DATABASE_ERROR: CANONICAL_ERROR_CODES.DATABASE_ERROR,
  SERVICE_UNAVAILABLE: CANONICAL_ERROR_CODES.SERVICE_UNAVAILABLE,
  EXTERNAL_SERVICE_ERROR: CANONICAL_ERROR_CODES.EXTERNAL_SERVICE_ERROR,
};

export function resolveErrorCodeAlias(code: string | undefined): CanonicalErrorCode | undefined {
  if (!code) {
    return undefined;
  }
  return ERROR_CODE_ALIASES_TO_CANONICAL[code];
}
